

name: deploy-container

on:
 push:
    branches:
      - master
    paths:
      - 'packages/container/**'
 workflow_dispatch: {} 

defaults:
 run:
     working-directory: packages/container

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install the dependencies
      - run: npm install

      # Build the container
      - run: npm run build
        env:
          PRODUCTION_DOMAIN: ${{ secrets.PRODUCTION_DOMAIN }}

      # Configure AWS CLI
      - uses: shinyinc/action-aws-cli@v1.2

      # Sync the built container to the S3 bucket
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1

      # Invalidate the CloudFront cache
      - run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/container/latest/index.html"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-east-1
#
#In this GitHub Actions workflow, the container is built and deployed to AWS S3 and CloudFront. The workflow is triggered on pushes to the master branch and workflow dispatches.
#
#The steps in the workflow are:
#
#1. Checkout the repository.
#2. Install the dependencies.
#3. Build the container.
#4. Configure AWS CLI.
#5. Sync the built container to the S3 bucket.
#6. Invalidate the CloudFront cache.
#
#The comments provide a clear and concise explanation of each step..</s>